In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\Users\TANAYA NEVE\Downloads\Class 2.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3274103278.py, line 1)

In [3]:
df = pd.read_csv(r"C:\Users\TANAYA NEVE\Downloads\class 2.csv")

In [4]:
df.head()

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
0,1,India,1471891,248045828,9807600,50.0,29.4,9.8,10.8,48.7,25.4,14.9,10.9,24.0,28.6,16.2,31.1
1,2,Andaman and Nicobar Islands,412,72119,5750,50.7,19.2,13.1,17.0,46.1,23.6,15.9,14.4,17.3,16.9,17.5,48.3
2,3,Andhra Pradesh,61373,8741885,338293,61.5,13.5,18.9,6.1,46.1,25.7,16.5,11.6,28.6,14.0,42.7,14.7
3,4,Arunachal Pradesh,3490,323717,24700,48.6,36.8,9.5,5.2,53.7,24.0,13.4,8.9,19.1,42.6,20.6,17.6
4,5,Assam,56630,6922533,342199,66.2,16.7,12.5,4.7,53.4,25.1,14.3,7.2,32.6,20.5,29.1,17.8

xxx

In [5]:
df[["India/State/UT", "Total Number of - Schools"]]

                              India/State/UT  Total Number of - Schools
0                                      India                    1471891
1                Andaman and Nicobar Islands                        412
2                             Andhra Pradesh                      61373
3                          Arunachal Pradesh                       3490
4                                      Assam                      56630
5                                      Bihar                      94686
6                                 Chandigarh                        230
7                               Chhattisgarh                      56615
8   Dadra and Nagar Haveli and Daman and Diu                        432
9                                      Delhi                       5497
10                                       Goa                       1487
11                                   Gujarat                      53626
12                                   Haryana                      23517
13                          Himachal Pradesh                      17826
14                         Jammu and Kashmir                      24296
15                                 Jharkhand                      44475
16                                 Karnataka                      75869
17                                    Kerala                      15864
18                                    Ladakh                        995
19                               Lakshadweep                         37
20                            Madhya Pradesh                     123412
21                               Maharashtra                     108237
22                                   Manipur                       4646
23                                 Meghalaya                      14601
24                                   Mizoram                       3941
25                                  Nagaland                       2725
26                                    Odisha                      61693
27                                Puducherry                        735
28                                    Punjab                      27404
29                                 Rajasthan                     107757
30                                    Sikkim                       1254
31                                Tamil Nadu                      58722
32                                 Telangana                      42901
33                                   Tripura                       4923
34                             Uttar Pradesh                     255087
35                               Uttarakhand                      22551
36                               West Bengal                      93945

In [6]:
df.columns

Index(['Sl. No.', 'India/State/UT', 'Total Number of - Schools',
       'Total Number of - Enrolments', 'Total Number of - Teachers',
       'Percentage Share of Schools by Category - Primary',
       'Percentage Share of Schools by Category - Upper Primary',
       'Percentage Share of Schools by Category - Secondary',
       'Percentage Share of Schools by Category - Higher Secondary',
       'Percentage Share of Enrolments by level -  Primary ',
       'Percentage Share of Enrolments by level -  Upper Primary ',
       'Percentage Share of Enrolments by level - Secondary',
       'Percentage Share of Enrolments by level - Higher Secondary',
       'Percentage Share of Teachers by School Category - Primary',
       'Percentage Share of Teachers by School Category - Upper Primary',
       'Percentage Share of Teachers by School Category - Secondary',
       'Percentage Share of Teachers by School Category - Higher Secondary'],
      dtype='str')

In [7]:
df.shape

(37, 17)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Sl. No.                                                             37 non-null     int64
 1   India/State/UT                                                      37 non-null     str
 2   Total Number of - Schools                                           37 non-null     int64
 3   Total Number of - Enrolments                                        37 non-null     int64
 4   Total Number of - Teachers                                          37 non-null     int64
 5   Percentage Share of Schools by Category - Primary                   37 non-null     float64
 6   Percentage Share of Schools by Category - Upper Primary             37 non-null     float64
 7   Percentage Share of Schools by Category - Secondary                 37 non-null     float64
 8   Percentage Share of Schools by Category - Higher Secondary          37 non-null     float64
 9   Percentage Share of Enrolments by level -  Primary                  37 non-null     float64
 10  Percentage Share of Enrolments by level -  Upper Primary            37 non-null     float64
 11  Percentage Share of Enrolments by level - Secondary                 37 non-null     float64
 12  Percentage Share of Enrolments by level - Higher Secondary          37 non-null     float64
 13  Percentage Share of Teachers by School Category - Primary           37 non-null     float64
 14  Percentage Share of Teachers by School Category - Upper Primary     37 non-null     float64
 15  Percentage Share of Teachers by School Category - Secondary         37 non-null     float64
 16  Percentage Share of Teachers by School Category - Higher Secondary  37 non-null     float64
dtypes: float64(12), int64(4), str(1)
memory usage: 5.0 KB

In [9]:
df["school name"].nuniquel()

KeyError: 'school name'

In [10]:
df["School Name"].nunique()

KeyError: 'School Name'

In [11]:
df["School Name"].nunique()

KeyError: 'School Name'

In [12]:
list(df.columns)

['Sl. No.',
 'India/State/UT',
 'Total Number of - Schools',
 'Total Number of - Enrolments',
 'Total Number of - Teachers',
 'Percentage Share of Schools by Category - Primary',
 'Percentage Share of Schools by Category - Upper Primary',
 'Percentage Share of Schools by Category - Secondary',
 'Percentage Share of Schools by Category - Higher Secondary',
 'Percentage Share of Enrolments by level -  Primary ',
 'Percentage Share of Enrolments by level -  Upper Primary ',
 'Percentage Share of Enrolments by level - Secondary',
 'Percentage Share of Enrolments by level - Higher Secondary',
 'Percentage Share of Teachers by School Category - Primary',
 'Percentage Share of Teachers by School Category - Upper Primary',
 'Percentage Share of Teachers by School Category - Secondary',
 'Percentage Share of Teachers by School Category - Higher Secondary']

In [13]:
df.sort_values(
    by="Total Number of - Enrolments",
    ascending=False
).head(10)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
0,1,India,1471891,248045828,9807600,50.0,29.4,9.8,10.8,48.7,25.4,14.9,10.9,24.0,28.6,16.2,31.1
34,35,Uttar Pradesh,255087,41662794,1538479,52.3,34.0,4.7,9.0,49.4,25.4,13.7,11.5,36.6,34.1,5.6,23.7
21,22,Maharashtra,108237,21375970,738114,46.1,27.0,16.5,10.4,44.2,25.9,16.9,13.0,18.9,27.1,25.1,28.8
5,6,Bihar,94686,21348149,657063,44.0,42.7,2.0,11.2,54.1,26.4,11.7,7.7,23.9,54.7,3.2,18.2
36,37,West Bengal,93945,18015525,576557,79.3,9.2,3.5,8.1,47.0,24.5,17.0,11.5,52.2,6.7,6.5,34.6
29,30,Rajasthan,107757,16786065,775745,35.0,32.0,6.8,26.1,49.6,24.7,14.5,11.2,10.8,28.8,9.2,51.2
20,21,Madhya Pradesh,123412,15361543,639525,49.4,35.7,6.7,8.2,51.2,25.9,13.9,9.0,21.2,37.9,11.6,29.4
31,32,Tamil Nadu,58722,12993050,550558,57.9,17.1,9.7,15.3,45.7,24.6,15.9,13.8,20.6,13.2,12.5,53.8
16,17,Karnataka,75869,11926303,433942,30.9,40.0,21.5,7.6,46.0,26.5,17.3,10.2,10.9,34.2,38.7,16.2
11,12,Gujarat,53626,11496709,394053,25.2,50.4,8.3,16.0,48.6,27.6,14.9,8.9,8.6,56.1,6.0,29.3

In [14]:
df.sort_values(
    by="Total Number of - Enrolments",
    ascending=False
).head(10)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
0,1,India,1471891,248045828,9807600,50.0,29.4,9.8,10.8,48.7,25.4,14.9,10.9,24.0,28.6,16.2,31.1
34,35,Uttar Pradesh,255087,41662794,1538479,52.3,34.0,4.7,9.0,49.4,25.4,13.7,11.5,36.6,34.1,5.6,23.7
21,22,Maharashtra,108237,21375970,738114,46.1,27.0,16.5,10.4,44.2,25.9,16.9,13.0,18.9,27.1,25.1,28.8
5,6,Bihar,94686,21348149,657063,44.0,42.7,2.0,11.2,54.1,26.4,11.7,7.7,23.9,54.7,3.2,18.2
36,37,West Bengal,93945,18015525,576557,79.3,9.2,3.5,8.1,47.0,24.5,17.0,11.5,52.2,6.7,6.5,34.6
29,30,Rajasthan,107757,16786065,775745,35.0,32.0,6.8,26.1,49.6,24.7,14.5,11.2,10.8,28.8,9.2,51.2
20,21,Madhya Pradesh,123412,15361543,639525,49.4,35.7,6.7,8.2,51.2,25.9,13.9,9.0,21.2,37.9,11.6,29.4
31,32,Tamil Nadu,58722,12993050,550558,57.9,17.1,9.7,15.3,45.7,24.6,15.9,13.8,20.6,13.2,12.5,53.8
16,17,Karnataka,75869,11926303,433942,30.9,40.0,21.5,7.6,46.0,26.5,17.3,10.2,10.9,34.2,38.7,16.2
11,12,Gujarat,53626,11496709,394053,25.2,50.4,8.3,16.0,48.6,27.6,14.9,8.9,8.6,56.1,6.0,29.3